---
title: TBD
author:
  - name: Sam Tyner
    email: sctyner90@gmail.com
    affiliation: TBD
    footnote: Corresponding Author
address:
  - code: Some Institute of Technology
    address: Department, Street, City, State, Zip
abstract: |
  This is the abstract.

  It consists of two paragraphs.

journal: "Forensic Science International"
date: "`r Sys.Date()`"
bibliography: mybibfile.bib
output: rticles::elsevier_article
---

_Text based on elsarticle sample manuscript, see [http://www.elsevier.com/author-schemas/latex-instructions#elsarticle](http://www.elsevier.com/author-schemas/latex-instructions#elsarticle)_


# Introduction

- Begin with a short discussion about *Likelihood ratio as weight of forensic evidence: a closer look* [@lundiyer17] 
    * Not every CDF in KS bounds is reasonable
    * Range of LRs given, but not a distribution.
    * Within the range, some LRs are going to be more likely than others 
- Moving in a different direction 
    * Don't look at the data first 
    * Use only knowledge about the problem to select range of possible distributions 
    * Define the constraints you wish to place on the distribution of CDFs (or on CDFs themselves?)
    * Use Dirichlet Process priors to get a range of plausible values
- Specific application(s)
    * Come up with range of plausible LRs for RI values in glass data:
        * What is the distribution of RI in glass from the same pane? 
        * What is the distribution of RI in all glass from the relevant population? 
    * (Maybe) Range of plausible SLRs for RF scores for element concentrations in glass data
        * What is the distribution of scores for known mates? 
        * What is the distribution of scores for known non-mates? 

# Dirichlet Process Priors

- Motivation: 
    * Bayesian way
    * Know very little about the shape, family, etc of the distribution
    * Simulate random CDFs from many priors
    * Check that they fit a set of constraints
    * Obtain posterior distribution of CDFs to get interval of plausible values of interest
- Theory: 
    * A little bit about what Dirichlet Process Priors are 
    * Not too technical for a forensic science audience
    * Stick breaking procedure
    * Size of M dictates how much to weigh data vs. base measure in the posterior 
    * Posterior: pick a random data point or pick a random value from the base measure 
- Application: 
    * Computer simulation: pick many Ms, base distributions, bounds/constraints.
    * Approximation 
    * Mention the `dprocsim` package 

# Simulation study 

## Likelihood ratio for RI data 

Two distributions, (1) RI for glass from the same pane, [@evett77, @curranR] (2) RI for glass from different panes [@lambertevett84]

- What is previously known about glass data from Lindley paper and others? 

- Bounds on CDF: smoothed 80% and 95% KS bands 

- simulation steps: 
    * Pick some Ms, some base distributions 
    * Simulate cdfs from them 
    * Check the criteria
    * Get the posteriors from them 
    * Get a distribution of possible values of $f_p, f_d$ for mean of "suspect" sample
    * Get a distribution of LRs. (How to turn two distributions of $f_p, f_d$ into another distribution?)

## Score-based likelihood ratio for random forest scores 

Two distributions, (1) scores for known mates, (2) scores for known non-mates [@park19]

- What do we know/assume about the distribution of the scores? 

- Restrictions on the CDF itself: no more than __% chance of being above/below the threshold (.5), positive probability everywhere 

- simulation steps: 
    * Pick some Ms, some base distributions 
    * Simulate cdfs from them 
    * Check the criteria
    * Get the posteriors from them 
    * Get a distribution of possible values of $f_p, f_d$ for some fixed score (.6?)
    * Get a distribution of SLRs. (How to turn two distributions of $f_p, f_d$ into another distribution?)

- I'm not quite sure how to get a distribution of LRs/SLRs from the distributions of $f_p, f_d$. 
    * Idea: Draw one sample from $f_p$, draw another from $f_d$. Compute LR/SLR. Repeat large $B$ times. (??)

# Discussion

- We have a distribution of values for $f_p, f_d$, which we turned into a LR, SLR
- There is inherent uncertainty in the assumptions made. 
    * this might not matter all that much in a more traditional statistical problem, but it could make a large difference in the LR/SLR values in the forensic science context, which has huge impact on people's lives. 
    
- More information, transparency in the decision making process. Be clear about assumptions and beliefs, and accept that others who are reasonable could make different assumptions and come up with different answers.
- We have examined just how different those answers could be when making reasonable assumptions
    

# References {#references .unnumbered}

