---
title: TBD
author:
  - name: Sam Tyner
    email: sctyner90@gmail.com
    affiliation: TBD
    footnote: Corresponding Author
address:
  - code: Some Institute of Technology
    address: Department, Street, City, State, Zip
abstract: |
  This is the abstract.

  It consists of two paragraphs.

journal: "Forensic Science International"
date: "`r Sys.Date()`"
bibliography: mybibfile.bib
output: rticles::elsevier_article
---

# Introduction

- Begin with a short discussion about *Likelihood ratio as weight of forensic evidence: a closer look* [@lundiyer17] 
    * Not every CDF in KS bounds is reasonable
    * Range of LRs given, but not a distribution.
    * Within the range, some LRs are going to be more likely than others 
- Moving in a different direction 
    * Use diffuse Dirichlet Process priors 
    * with enough data, can go straight to the posterior DP(n, $\hat{F}_n$) [@draper17]
- Specific application(s)
    * Come up with range of plausible LRs for RI values in glass data:
        * distribution for pane means [@curranpkg]
        * distribution for measurements within a pane [@lambertevett84]
    * Range of plausible SLRs for RF scores for element concentrations in glass data
        * What is the distribution of scores for known mates? 
        * What is the distribution of scores for known non-mates? 

# Dirichlet Process Priors

- Motivation: 
    * Bayesian way
    * Know very little about the shape, family, etc of the distribution
    * Go straight to the posterior: Obtain posterior distribution of CDFs to get interval of plausible values of interest
- Theory: 
    * A little bit about what Dirichlet Process Priors are 
    * Not too technical for a forensic science audience
    * Stick breaking procedure
    * Let M go to zero. When data are large, M is small, the posterior distribution converges to almost bootstrap [@draper17]
- Application: 
    * Computer simulation from the posterior.
    * Approximation 
    * Mention the `dprocsim` package as the tool.

# Simulation study 

## Likelihood ratio for RI data 

Refractive Index (RI) is a measurment of how light bends through a medium. In @evett77, @lambertevett84 and others RI is suggested as a method to determine if recovered glass fragments could have come from a known source of glass, such as a broken window at a crime scene. 


Two scenarios, (1) RI for glass from the same pane, [@curranpkg] (2) RI for glass from different panes [@lambertevett84]

What are the distributions of interest: 

1. distribution of the mean/median RI values in a pane. The population distribution of these means is of interest. 
2. distribution of the RI values within one pane of glass. 

Quantity of Interest: 

$$LR = \frac{\int_{\Theta} f(x,y | \theta) g(\theta) d\theta}{\int_{\Theta} f(x | \theta) g(\theta) d\theta \times \int_{\Theta} f(y | \theta) g(\theta) d\theta}$$

- Where $X$ is the glass sample from the crime scene, and $y$ is the glass recovered from the suspect. 

<!--
- What is previously known about glass data from Evett paper and others? 

- Bounds on CDF: ~~smoothed 80% and 95% KS bands~~ p-box around the base distributions
    * for "prosecutor's hypothesis": base distribution is Normal($\bar{X}$, $\sigma = 4\times10^{-5}$) where $\bar{X}$ is the sample mean from the known source of glass [@evett77]
    * for "defense hypothesis": base distribution is a mixture of normals with the same $\sigma = 4\times10^{-5}$. Per population data examined in @lambertevett84, "most of the samples are centered around and RI of 1.5175 with smaller groups near 1.5192 and 1.5220. So, we'll use three normal distributions with means 1.5175, 1.5192, and 1.5220 and mixture weights .6, .2, and .2, respectively. We use the common standard deviation of $\sigma = 4\times10^{-5}$. 
    * how to construct the p-box around the true cdfs? 
--> 


- simulation steps: 
    1. Go straight to the posterior: Simulate a cdf from F, G (subtract the median from the data for F: location family)
    2. Get a grid of median values you're interested in. 
    3. For each median ($\theta$) in the grid:
        a. Compute G($\theta + \epsilon$) - G($\theta - \epsilon$) for some small $\epsilon$ (e.g. 0.0001)
        b. Compute F($x-\theta + \epsilon$) - F($x-\theta - \epsilon$) for some small $\epsilon$ (e.g. 0.0001) for all values in the data of interest (crime scene sample + suspect sample)
    4. Multiply results from 3b together, then multiply that result by 3a. (for the numerator) 
    5. Multiply the results from 3b by group: crime scene sample only, then suspect sample only.
    6. multiply 3a by each value from 5. 
    7. Sum the results from 6 in their groups (two integrals), then multiply the sums together.
    8. Sum the results from 4, then divide by result from 7. This is the LR. 
- Repeat the above process many times until a distribution of LRs is acheived. (1000+ times)

## Score-based likelihood ratio for random forest scores 

Two distributions, (1) scores for known mates, (2) scores for known non-mates [@park19]

- Go straight to the posterior again. 

- simulation steps: 
    1. Go straight to the posterior: Simulate a cdf from $F_p$, $F_d$
    2. Over a grid of scores (0-1), compute 
        a. $F_p(s+\epsilon) - F_p(s-\epsilon)$
        b. $F_d(s+\epsilon) - F_d(s-\epsilon)$
    3. Divide $F_p / F_d$ for each score in the grid. This is the LR. 
    4. For a particular score of interest, report the LR.
- Repeat the above process many times to obtain a distribution of the LR for that particular score of interest. 

# Discussion

- We have a distribution of values for $f_p, f_d$, which we turned into a LR, SLR
- There is inherent uncertainty in the assumptions made. 
    * this might not matter all that much in a more traditional statistical problem, but it could make a large difference in the LR/SLR values in the forensic science context, which has huge impact on people's lives. 
    
- More information, transparency in the decision making process. Be clear about assumptions and beliefs, and accept that others who are reasonable could make different assumptions and come up with different answers.
- We have examined just how different those answers could be when making reasonable assumptions
    

# References {#references .unnumbered}

